import createFormData from 'shared/utils/createFormData';
import { clearFormID } from 'shared/utils/createFormID';
// data from backend
import allTaskFormProperties from '../../schema/allTaskFormProperties';

describe('shared/utils/createFormData', () => {
  afterEach(() => {
    clearFormID();
  });

  it('createFormData should be a function', () => {
    expect(createFormData).toBeInstanceOf(Function);
  });

  it('createFormData should works fine', () => {
    const { formPropertyVO } = allTaskFormProperties[0];
    const result = {
      formProperty: [
        {
          id: 'commercialId',
          name: '商户编号',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 1,
        },
        {
          id: 'commercialName',
          name: '商户名称',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 2,
        },
        {
          id: 'brandName',
          name: '品牌名称',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 3,
        },
        {
          id: 'businessConsultant',
          name: '业务顾问',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 4,
        },
        {
          id: 'businessConsultantPhone',
          name: '业务顾问电话',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 5,
        },
        {
          id: 'businessContacts',
          name: '商户联系人',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 6,
        },
        {
          id: 'commercialAddress',
          name: '详细地址',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 7,
        },
        {
          id: 'contractWay',
          name: '联系方式',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 8,
        },
        {
          id: 'serviceConsultant',
          name: '服务顾问',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 9,
        },
        {
          id: 'serviceConsultantPhone',
          name: '服务顾问电话',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 10,
        },
        {
          id: 'serviceType',
          name: '服务类型',
          type: 'enum',
          itemCount: 0,
          parentId: '',
          formExtendID: 11,
        },
        {
          id: 'serviceStartDate',
          name: '合约日期',
          type: 'date',
          itemCount: 0,
          parentId: '',
          formExtendID: 12,
        },
        {
          id: 'serviceEndDate',
          name: '合约日期',
          type: 'date',
          itemCount: 0,
          parentId: '',
          formExtendID: 13,
        },
        {
          id: 'serviceTimes',
          name: '服务次数',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 14,
        },
        {
          id: 'serviceConfirmFiles',
          name: '服务确认单',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 15,
        },
        {
          id: 'letterOfCommitment',
          name: '承诺书',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 16,
        },
      ],
      formExtend: [
        {
          children: [
            {
              children: [
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 1,
                        type: 'Input',
                      },
                    ],
                    col: 1,
                    order: 1,
                    row: 1,
                    span: 12,
                  },
                  id: 1,
                  label: '商户编号',
                  parentId: 18,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'commercialId',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 2,
                        type: 'Input',
                      },
                    ],
                    col: 2,
                    order: 2,
                    row: 1,
                    span: 12,
                  },
                  id: 2,
                  label: '商户名称',
                  parentId: 18,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'commercialName',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 3,
                        type: 'Input',
                      },
                    ],
                    col: 1,
                    order: 3,
                    row: 2,
                    span: 12,
                  },
                  id: 3,
                  label: '品牌名称',
                  parentId: 18,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'brandName',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 4,
                        type: 'Input',
                      },
                    ],
                    col: 2,
                    order: 4,
                    row: 2,
                    span: 12,
                  },
                  id: 4,
                  label: '业务顾问',
                  parentId: 18,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'businessConsultant',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 5,
                        type: 'Input',
                      },
                    ],
                    col: 1,
                    order: 5,
                    row: 3,
                    span: 12,
                  },
                  id: 5,
                  label: '业务顾问电话',
                  parentId: 18,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'businessConsultantPhone',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 6,
                        type: 'Input',
                      },
                    ],
                    col: 2,
                    order: 6,
                    row: 3,
                    span: 12,
                  },
                  id: 6,
                  label: '商户联系人',
                  parentId: 18,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'businessContacts',
                  row: null,
                  type: 'Input',
                },
              ],
              col: 2,
              id: 18,
              isLayout: true,
              parentId: 17,
              row: 3,
              sectionName: '基础资料',
              tabKey: undefined,
              type: 'Grid',
            },
            {
              children: [
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 2,
                        type: 'Column',
                      },
                      {
                        order: 1,
                        type: 'Input',
                      },
                    ],
                    col: 1,
                    order: 7,
                    row: 1,
                    span: 12,
                  },
                  id: 7,
                  label: '详细地址',
                  parentId: 19,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'commercialAddress',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 2,
                        type: 'Column',
                      },
                      {
                        order: 2,
                        type: 'Input',
                      },
                    ],
                    col: 2,
                    order: 8,
                    row: 1,
                    span: 12,
                  },
                  id: 8,
                  label: '联系方式',
                  parentId: 19,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'contractWay',
                  row: null,
                  type: 'Input',
                },
              ],
              col: 2,
              id: 19,
              isLayout: true,
              parentId: 17,
              row: 1,
              sectionName: '基础资料',
              tabKey: undefined,
              type: 'Column',
            },
          ],
          col: null,
          id: 17,
          isLayout: true,
          parentId: 0,
          row: null,
          sectionName: '基础资料',
          tabKey: undefined,
          type: 'Panel',
        },
        {
          children: [
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 1,
                    type: 'Input',
                  },
                ],
                col: 1,
                order: 9,
                row: 1,
                span: 8,
              },
              id: 9,
              label: '服务顾问',
              parentId: 20,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceConsultant',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 2,
                    type: 'Input',
                  },
                ],
                col: 2,
                order: 10,
                row: 1,
                span: 8,
              },
              id: 10,
              label: '服务顾问电话',
              parentId: 20,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceConsultantPhone',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 3,
                    type: 'Input',
                  },
                ],
                col: 3,
                order: 11,
                row: 1,
                span: 8,
              },
              id: 11,
              label: '服务类型',
              parentId: 20,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceType',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 4,
                    type: 'Input',
                  },
                ],
                col: 1,
                order: 12,
                row: 2,
                span: 8,
              },
              id: 12,
              label: '合约日期',
              parentId: 20,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceStartDate',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 5,
                    type: 'Input',
                  },
                ],
                col: 2,
                order: 13,
                row: 2,
                span: 8,
              },
              id: 13,
              label: '合约日期',
              parentId: 20,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceEndDate',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 6,
                    type: 'Input',
                  },
                ],
                col: 3,
                order: 14,
                row: 2,
                span: 8,
              },
              id: 14,
              label: '服务次数',
              parentId: 20,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceTimes',
              row: null,
              type: 'Input',
            },
          ],
          col: 3,
          id: 20,
          isLayout: true,
          parentId: 0,
          row: 2,
          sectionName: null,
          tabKey: undefined,
          type: 'Grid',
        },
        {
          children: [
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 3,
                    type: 'Column',
                  },
                  {
                    order: 1,
                    type: 'Input',
                  },
                ],
                col: 1,
                order: 15,
                row: 1,
                span: 12,
              },
              id: 15,
              label: '服务确认单',
              parentId: 21,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceConfirmFiles',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 3,
                    type: 'Column',
                  },
                  {
                    order: 2,
                    type: 'Input',
                  },
                ],
                col: 2,
                order: 16,
                row: 1,
                span: 12,
              },
              id: 16,
              label: '承诺书',
              parentId: 21,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'letterOfCommitment',
              row: null,
              type: 'Input',
            },
          ],
          col: 2,
          id: 21,
          isLayout: true,
          parentId: 0,
          row: 1,
          sectionName: null,
          tabKey: undefined,
          type: 'Column',
        },
      ],
    };

    expect(createFormData(formPropertyVO)).toEqual(result);
  });

  it('createFormData should works fine, when received data has list type', () => {
    const { formPropertyVO } = allTaskFormProperties[1];
    const result = {
      formProperty: [
        {
          id: 'commercialId',
          name: '商户编号',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 1,
        },
        {
          id: 'commercialName',
          name: '商户名称',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 2,
        },
        {
          id: 'brandName',
          name: '品牌名称',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 3,
        },
        {
          id: 'businessConsultant',
          name: '业务顾问',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 4,
        },
        {
          id: 'businessConsultantPhone',
          name: '业务顾问电话',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 5,
        },
        {
          id: 'businessContacts',
          name: '商户联系人',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 6,
        },
        {
          id: 'commercialAddress',
          name: '详细地址',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 7,
        },
        {
          id: 'contractWay',
          name: '联系方式',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 8,
        },
        {
          id: 'serviceConsultant',
          name: '服务顾问',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 9,
        },
        {
          id: 'serviceConsultantPhone',
          name: '服务顾问电话',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 10,
        },
        {
          id: 'serviceType',
          name: '服务类型',
          type: 'enum',
          itemCount: 0,
          parentId: '',
          formExtendID: 11,
        },
        {
          id: 'serviceStartDate',
          name: '合约日期',
          type: 'date',
          itemCount: 0,
          parentId: '',
          formExtendID: 12,
        },
        {
          id: 'serviceEndDate',
          name: '合约日期',
          type: 'date',
          itemCount: 0,
          parentId: '',
          formExtendID: 13,
        },
        {
          id: 'serviceTimes',
          name: '服务次数',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 14,
        },
        {
          id: 'serviceConfirmFiles',
          name: '服务确认单',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 15,
        },
        {
          id: 'letterOfCommitment',
          name: '承诺书',
          type: 'string',
          itemCount: 0,
          parentId: '',
          formExtendID: 16,
        },
        {
          id: 'dynamicListTest',
          name: '动态组件测试',
          type: 'list',
          itemCount: 2,
          parentId: '',
          formExtendID: 17,
        },
        {
          id: 'serviceName',
          name: '服务名称',
          type: 'string',
          itemCount: 0,
          parentId: 'dynamicListTest',
          formExtendID: 18,
        },
        {
          id: 'serviceNumber',
          name: '服务次数',
          type: 'string',
          itemCount: 0,
          parentId: 'dynamicListTest',
          formExtendID: 19,
        },
      ],
      formExtend: [
        {
          children: [
            {
              children: [
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 1,
                        type: 'Input',
                      },
                    ],
                    col: 1,
                    order: 1,
                    row: 1,
                    span: 12,
                  },
                  id: 1,
                  label: '商户编号',
                  parentId: 21,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'commercialId',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 2,
                        type: 'Input',
                      },
                    ],
                    col: 2,
                    order: 2,
                    row: 1,
                    span: 12,
                  },
                  id: 2,
                  label: '商户名称',
                  parentId: 21,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'commercialName',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 3,
                        type: 'Input',
                      },
                    ],
                    col: 1,
                    order: 3,
                    row: 2,
                    span: 12,
                  },
                  id: 3,
                  label: '品牌名称',
                  parentId: 21,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'brandName',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 4,
                        type: 'Input',
                      },
                    ],
                    col: 2,
                    order: 4,
                    row: 2,
                    span: 12,
                  },
                  id: 4,
                  label: '业务顾问',
                  parentId: 21,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'businessConsultant',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 5,
                        type: 'Input',
                      },
                    ],
                    col: 1,
                    order: 5,
                    row: 3,
                    span: 12,
                  },
                  id: 5,
                  label: '业务顾问电话',
                  parentId: 21,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'businessConsultantPhone',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 1,
                        type: 'Grid',
                      },
                      {
                        order: 6,
                        type: 'Input',
                      },
                    ],
                    col: 2,
                    order: 6,
                    row: 3,
                    span: 12,
                  },
                  id: 6,
                  label: '商户联系人',
                  parentId: 21,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'businessContacts',
                  row: null,
                  type: 'Input',
                },
              ],
              col: 2,
              id: 21,
              isLayout: true,
              parentId: 20,
              row: 3,
              sectionName: '基础资料',
              tabKey: undefined,
              type: 'Grid',
            },
            {
              children: [
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 2,
                        type: 'Column',
                      },
                      {
                        order: 1,
                        type: 'Input',
                      },
                    ],
                    col: 1,
                    order: 7,
                    row: 1,
                    span: 12,
                  },
                  id: 7,
                  label: '详细地址',
                  parentId: 22,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'commercialAddress',
                  row: null,
                  type: 'Input',
                },
                {
                  children: null,
                  col: null,
                  componentConfig: undefined,
                  defaultValue: undefined,
                  formItemConfig: undefined,
                  grid: {
                    chain: [
                      {
                        order: 1,
                        type: 'Panel',
                      },
                      {
                        order: 2,
                        type: 'Column',
                      },
                      {
                        order: 2,
                        type: 'Input',
                      },
                    ],
                    col: 2,
                    order: 8,
                    row: 1,
                    span: 12,
                  },
                  id: 8,
                  label: '联系方式',
                  parentId: 22,
                  patterns: undefined,
                  placeholder: undefined,
                  propertyID: 'contractWay',
                  row: null,
                  type: 'Input',
                },
              ],
              col: 2,
              id: 22,
              isLayout: true,
              parentId: 20,
              row: 1,
              sectionName: '基础资料',
              tabKey: undefined,
              type: 'Column',
            },
          ],
          col: null,
          id: 20,
          isLayout: true,
          parentId: 0,
          row: null,
          sectionName: '基础资料',
          tabKey: undefined,
          type: 'Panel',
        },
        {
          children: [
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 1,
                    type: 'Input',
                  },
                ],
                col: 1,
                order: 9,
                row: 1,
                span: 8,
              },
              id: 9,
              label: '服务顾问',
              parentId: 23,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceConsultant',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 2,
                    type: 'Input',
                  },
                ],
                col: 2,
                order: 10,
                row: 1,
                span: 8,
              },
              id: 10,
              label: '服务顾问电话',
              parentId: 23,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceConsultantPhone',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 3,
                    type: 'Input',
                  },
                ],
                col: 3,
                order: 11,
                row: 1,
                span: 8,
              },
              id: 11,
              label: '服务类型',
              parentId: 23,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceType',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 4,
                    type: 'Input',
                  },
                ],
                col: 1,
                order: 12,
                row: 2,
                span: 8,
              },
              id: 12,
              label: '合约日期',
              parentId: 23,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceStartDate',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 5,
                    type: 'Input',
                  },
                ],
                col: 2,
                order: 13,
                row: 2,
                span: 8,
              },
              id: 13,
              label: '合约日期',
              parentId: 23,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceEndDate',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 2,
                    type: 'Grid',
                  },
                  {
                    order: 6,
                    type: 'Input',
                  },
                ],
                col: 3,
                order: 14,
                row: 2,
                span: 8,
              },
              id: 14,
              label: '服务次数',
              parentId: 23,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceTimes',
              row: null,
              type: 'Input',
            },
          ],
          col: 3,
          id: 23,
          isLayout: true,
          parentId: 0,
          row: 2,
          sectionName: null,
          tabKey: undefined,
          type: 'Grid',
        },
        {
          children: [
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 3,
                    type: 'Column',
                  },
                  {
                    order: 1,
                    type: 'Input',
                  },
                ],
                col: 1,
                order: 15,
                row: 1,
                span: 12,
              },
              id: 15,
              label: '服务确认单',
              parentId: 24,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'serviceConfirmFiles',
              row: null,
              type: 'Input',
            },
            {
              children: null,
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 3,
                    type: 'Column',
                  },
                  {
                    order: 2,
                    type: 'Input',
                  },
                ],
                col: 2,
                order: 16,
                row: 1,
                span: 12,
              },
              id: 16,
              label: '承诺书',
              parentId: 24,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'letterOfCommitment',
              row: null,
              type: 'Input',
            },
          ],
          col: 2,
          id: 24,
          isLayout: true,
          parentId: 0,
          row: 1,
          sectionName: null,
          tabKey: undefined,
          type: 'Column',
        },
        {
          children: [
            {
              children: [
                {
                  children: [
                    {
                      children: null,
                      col: null,
                      componentConfig: undefined,
                      defaultValue: undefined,
                      formItemConfig: undefined,
                      grid: {
                        chain: [
                          {
                            order: 4,
                            type: 'Column',
                          },
                          {
                            order: 1,
                            type: 'DynamicList',
                          },
                          {
                            order: 1,
                            type: 'Column',
                          },
                          {
                            order: 1,
                            type: 'Input',
                          },
                        ],
                        col: 1,
                        order: 18,
                        row: 1,
                        span: 12,
                      },
                      id: 18,
                      label: '服务名称',
                      parentId: 26,
                      patterns: undefined,
                      placeholder: undefined,
                      propertyID: 'serviceName',
                      row: null,
                      type: 'Input',
                    },
                    {
                      children: null,
                      col: null,
                      componentConfig: undefined,
                      defaultValue: undefined,
                      formItemConfig: undefined,
                      grid: {
                        chain: [
                          {
                            order: 4,
                            type: 'Column',
                          },
                          {
                            order: 1,
                            type: 'DynamicList',
                          },
                          {
                            order: 1,
                            type: 'Column',
                          },
                          {
                            order: 2,
                            type: 'Input',
                          },
                        ],
                        col: 2,
                        order: 19,
                        row: 1,
                        span: 12,
                      },
                      id: 19,
                      label: '服务次数',
                      parentId: 26,
                      patterns: undefined,
                      placeholder: undefined,
                      propertyID: 'serviceNumber',
                      row: null,
                      type: 'Input',
                    },
                  ],
                  col: 2,
                  id: 26,
                  isLayout: true,
                  parentId: 17,
                  row: 1,
                  sectionName: null,
                  tabKey: undefined,
                  type: 'Column',
                },
              ],
              col: null,
              componentConfig: undefined,
              defaultValue: undefined,
              formItemConfig: undefined,
              grid: {
                chain: [
                  {
                    order: 4,
                    type: 'Column',
                  },
                  {
                    order: 1,
                    type: 'DynamicList',
                  },
                ],
                col: 1,
                order: 17,
                row: 1,
                span: 24,
              },
              id: 17,
              label: '动态组件测试',
              parentId: 25,
              patterns: undefined,
              placeholder: undefined,
              propertyID: 'dynamicListTest',
              row: null,
              type: 'DynamicList',
            },
          ],
          col: 1,
          id: 25,
          isLayout: true,
          parentId: 0,
          row: 1,
          sectionName: null,
          tabKey: undefined,
          type: 'Column',
        },
      ],
    };

    expect(createFormData(formPropertyVO)).toEqual(result);
  });
});
